spring.application.name=gestion-panaderia

#conexion a la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/base_panaderia
spring.datasource.username=postgres
spring.datasource.password=1995691
spring.datasource.driver-class-name=org.postgresql.Driver

#configuracion de jpa/hibernate
#le dice a spring boot que lea tus entities y cree las tabalas automaticamente sino existen
spring.jpa.hibernate.ddl-auto=update

#muestra en la consola de springboot el codigo sql que se esta ejecutando por detras
spring.jpa.show-sql=true

#formatea el sql en la consola para que sea mas facil de leer
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

